backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/"
media_library: "/"
collections:
  - name: "testimonials"
    create: true # users can create new documents